### ISSUE TITLE
Files not re-generated on version update?

### ISSUE THREAD

**Issue by in0ni** [Semantic-Org/Semantic-UI-Meteor#98] opened 2016-07-12 04:32 UTC
(original post is now invalid see comment below)
most of the sizes do not work, since the bundled less file (steps.import.less) only has the `small` and `large` sizes:

`
.ui.small.step,
.ui.small.steps .step {
  font-size: @small;
}
.ui.step,
.ui.steps .step {
  font-size: @medium;
}
.ui.large.step,
.ui.large.steps .step {
  font-size: @large;
}
`

while the [current less file](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/elements/step.less) has them all properly listed:
`
.ui.mini.steps .step,
.ui.mini.step {
  font-size: @mini;
}
.ui.tiny.steps .step,
.ui.tiny.step {
  font-size: @tiny;
}
.ui.small.steps .step,
.ui.small.step {
  font-size: @small;
}
.ui.steps .step,
.ui.step {
  font-size: @medium;
}
.ui.large.steps .step,
.ui.large.step {
  font-size: @large;
}
.ui.big.steps .step,
.ui.big.step {
  font-size: @big;
}
.ui.huge.steps .step,
.ui.huge.step {
  font-size: @huge;
}
.ui.massive.steps .step,
.ui.massive.step {
  font-size: @massive;
}
`

unsure if this is related, but i recently upgraded the package to 2.2.1 -- didn't work before or after the update. also the file states its generated (in top comments) from version 2.1.8...

**Comment by in0ni** [comment] 2016-08-23 17:56
the issue here seems to be that when upgrading versions files are not automatically re-generated. once i had to edit custom.semantic.json it was fine. shouldn't all files be re-generated when there is an update? i'm changing title to reflect this...

**Comment by fvpDev** [comment] 2016-09-26 22:03
Duplicate of #82

**Closed as completed by fvpDev** 2016-09-26 22:03 UTC
