### ISSUE TITLE
Unknown import:    themes/default/globals/site.variables.import.less

### ISSUE THREAD

**Issue by klbjlabs** [Semantic-Org/Semantic-UI-Meteor#78] opened 2015-11-09 11:01 UTC
getting this on trying to use the package:

```
=> Your application has errors. Waiting for file change.
=> Modified -- restarting.                    
=> Errors prevented startup:                  

   While processing files with flemay:less-autoprefixer (for target web.browser):
   client/lib/theme.import.less:20: Unknown import:
   themes/default/globals/site.variables.import.less
```

**Comment by talha-asad** [comment] 2015-11-13 11:49
I don't get the import error, but i am unable to use colors in my less files. It says it's undefined, even though i am reference importing semantic ui and i also tried directly reference importing `site.variables.import.less` as well.

``` less
@import (reference) '../lib/semantic-ui/site/globals/site.variables.import.less';
```

can't use `@blue`

btw i am on 2.1.6

**Comment by sapiens-sapide** [comment] 2015-11-13 17:56
Same issue for me on a fresh, clean install of meteor, with solely semantic:ui and flemay:less-autoprefixer packages added, and with an empty custom.semantic.json file : 

```
#Errors prevented startup:

While processing files with flemay:less-autoprefixer (for target web.browser):
  client/lib/semantic-ui/theme.import.less:20: Unknown import: themes/default/globals/site.variables.import.less
```

**Comment by jlukic** [comment] 2015-11-13 18:55
Variables are scoped per component. `@blue` has a different meaning for each component, see guide on semantic-ui.com

**Comment by talha-asad** [comment] 2015-11-14 05:08
@jlukic Doesn't matter weather they are scoped per component or not, what i want to access is the color Blue that i have mentioned in my site theme, which is something pretty trivial and defeats the purpose of setting colors if you can't access them in your own less files.

**Comment by talha-asad** [comment] 2015-11-14 20:16
@flemay It seems this is a bug in less-autoprefixer

So if you want to reproduce, setup a few colors in your site theme in semantic-ui and then reference importing either semantic ui entirely or the `site.variables.import.less` file and using one of those color variables. Seems to be undefined.

**Comment by flemay** [comment] 2015-11-14 23:08
Does the `less` package work in this situation?

**Comment by jlukic** [comment] 2015-11-14 23:16
You should be able to `@import` `site.variables.import.less` and have access to any variables defined there. Just make sure you have paths correct 

Generally though, inheritance in SUI is scoped per-component. @blue could be defined in any one of 6 places.
http://learnsemantic.com/themes/overview.html

**Comment by micimize** [comment] 2016-01-18 22:22
I found the solution here worked: #74

**Comment by jeveloper** [comment] 2016-02-04 20:53
I'm seeing this issue with meteor 1.2.1 and latest semantic 
I tried getting rid of default (marking it false in json file) and leaving material , but it breaks , is that normal or rather expected behaviour ? Can someone confirm.
i can make it work by editing theme.config.import.less and change default to my theme but it would've been nice to just get rid of default theme altogether.

thanks

**Comment by aesmon** [comment] 2016-02-07 05:47
Same issue, unable to import after just adding the packages and deleting .custom.semantic.json

While processing files with flemay:less-autoprefixer (for target web.browser):
   client/lib/semantic/theme.import.less:16: Unknown import:
   themes//default/globals/site.variables

**Comment by breagan1983** [comment] 2016-02-23 04:34
+1 Exact same issue

**Comment by nooitaf** [comment] 2016-02-23 12:17
@jeveloper as soon as you set `default` to `false` in `custom.semantic.json` and save, meteor removes the `client/lib/themes/default/` folder, so the `'default'` pathname values in `theme.config.import` will present a wrong path down the line. 

There is also one file path thats hardcoded in `theme.import.less:20`

``` less
/* Default site.variables */
@import "@{themesFolder}/default/globals/site.variables.import.less";
```

So it might be a good idea to leave default installed.

Most, if not all, themes are just overrides of the default theme. So removing the default theme, might be more problematic and might force every thememaker to include everything. 

Why not just put your theme into the `/site` folder and leave it default? The `/themes` folder gets regenerated and shouldn't be edited anyway.

@aesmon did https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/74 work for you? 
As in ...
1. stop meteor
2. delete `.custom.semantic.json`
3. start meteor

I just did a fresh install of semantic and i also had to stop meteor before it generated the inital files and folders, maybe we should add that step to the docs too.

**Comment by arrygoo** [comment] 2016-07-09 18:51
I'm still having this issue on a fresh installation of Meteor and following the steps in the docs.

**Comment by KristerV** [comment] 2016-07-10 11:28
same here. deleting .custom.semantic.json makes no difference.

```
client/semantic-ui/theme.import.less:20: Unknown import: themes/default/globals/site.variables.import.less
```

Deleting everything but the original custom.semantic.json seems to be a temporary solution, doesn't help anymore.

This fixed it, but is a bad solution: https://forums.meteor.com/t/whats-up-with-semantic-ui/12331/12
Also this seems to shed light on the problem: https://github.com/meteor/meteor/issues/5598

**Real fix**
Ahhaa, seems that adding `site: true` to the definitions is mandatory, that's where the globals folder comes from. Also reset seems to be important for default styling.

**Comment by kevinkorte** [comment] 2016-08-26 05:25
thanks @KristerV, that fixed it for me as well

**Comment by fvpDev** [comment] 2016-09-27 14:14
Closing this

**Closed as completed by fvpDev** 2016-09-27 14:14 UTC

**Comment by faeb187** [comment] 2016-10-11 11:22
You need ONLY site: true, as soon as I removed unused definitions I got rid of all the errors which came after I just added site: true...

**Comment by ojczeo** [comment] 2019-11-14 15:01
this also helps:
https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/78#issuecomment-187677357
